export const DEFAULT_COUNTRIES = [
  { name: 'Egypt', phone_code: '20', emoji: '🇪🇬', iso2: 'EG', nationality: 'Egyptian' },
  { name: 'Saudi Arabia', phone_code: '966', emoji: '🇸🇦', iso2: 'SA', nationality: 'Saudi' },
  { name: 'United Arab Emirates', phone_code: '971', emoji: '🇦🇪', iso2: 'AE', nationality: 'Emirati' },
  { name: 'Kuwait', phone_code: '965', emoji: '🇰🇼', iso2: 'KW', nationality: 'Kuwaiti' },
  { name: 'Qatar', phone_code: '974', emoji: '🇶🇦', iso2: 'QA', nationality: 'Qatari' },
  { name: 'Bahrain', phone_code: '973', emoji: '🇧🇭', iso2: 'BH', nationality: 'Bahraini' },
  { name: 'Oman', phone_code: '968', emoji: '🇴🇲', iso2: 'OM', nationality: 'Omani' },
  { name: 'Jordan', phone_code: '962', emoji: '🇯🇴', iso2: 'JO', nationality: 'Jordanian' },
  { name: 'Lebanon', phone_code: '961', emoji: '🇱🇧', iso2: 'LB', nationality: 'Lebanese' },
  { name: 'Palestine', phone_code: '970', emoji: '🇵🇸', iso2: 'PS', nationality: 'Palestinian' },
  { name: 'Iraq', phone_code: '964', emoji: '🇮🇶', iso2: 'IQ', nationality: 'Iraqi' },
  { name: 'Syria', phone_code: '963', emoji: '🇸🇾', iso2: 'SY', nationality: 'Syrian' },
  { name: 'Yemen', phone_code: '967', emoji: '🇾🇪', iso2: 'YE', nationality: 'Yemeni' },
  { name: 'Libya', phone_code: '218', emoji: '🇱🇾', iso2: 'LY', nationality: 'Libyan' },
  { name: 'Sudan', phone_code: '249', emoji: '🇸🇩', iso2: 'SD', nationality: 'Sudanese' },
  { name: 'Algeria', phone_code: '213', emoji: '🇩🇿', iso2: 'DZ', nationality: 'Algerian' },
  { name: 'Morocco', phone_code: '212', emoji: '🇲🇦', iso2: 'MA', nationality: 'Moroccan' },
  { name: 'Tunisia', phone_code: '216', emoji: '🇹🇳', iso2: 'TN', nationality: 'Tunisian' },
  { name: 'Mauritania', phone_code: '222', emoji: '🇲🇷', iso2: 'MR', nationality: 'Mauritanian' },
  { name: 'United Kingdom', phone_code: '44', emoji: '🇬🇧', iso2: 'GB', nationality: 'British' },
  { name: 'United States', phone_code: '1', emoji: '🇺🇸', iso2: 'US', nationality: 'American' },
  { name: 'Canada', phone_code: '1', emoji: '🇨🇦', iso2: 'CA', nationality: 'Canadian' },
  { name: 'Germany', phone_code: '49', emoji: '🇩🇪', iso2: 'DE', nationality: 'German' },
  { name: 'France', phone_code: '33', emoji: '🇫🇷', iso2: 'FR', nationality: 'French' },
  { name: 'Italy', phone_code: '39', emoji: '🇮🇹', iso2: 'IT', nationality: 'Italian' },
  { name: 'Spain', phone_code: '34', emoji: '🇪🇸', iso2: 'ES', nationality: 'Spanish' },
  { name: 'Turkey', phone_code: '90', emoji: '🇹🇷', iso2: 'TR', nationality: 'Turkish' },
  { name: 'India', phone_code: '91', emoji: '🇮🇳', iso2: 'IN', nationality: 'Indian' },
  { name: 'Pakistan', phone_code: '92', emoji: '🇵🇰', iso2: 'PK', nationality: 'Pakistani' },
  { name: 'Bangladesh', phone_code: '880', emoji: '🇧🇩', iso2: 'BD', nationality: 'Bangladeshi' },
  { name: 'China', phone_code: '86', emoji: '🇨🇳', iso2: 'CN', nationality: 'Chinese' },
  { name: 'Japan', phone_code: '81', emoji: '🇯🇵', iso2: 'JP', nationality: 'Japanese' },
  { name: 'Australia', phone_code: '61', emoji: '🇦🇺', iso2: 'AU', nationality: 'Australian' },
  { name: 'New Zealand', phone_code: '64', emoji: '🇳🇿', iso2: 'NZ', nationality: 'New Zealander' },
];
 