export const DEFAULT_COUNTRIES = [
  { name: 'Egypt', phone_code: '20', emoji: '🇪🇬', iso2: 'EG' },
  { name: 'Saudi Arabia', phone_code: '966', emoji: '🇸🇦', iso2: 'SA' },
  { name: 'United Arab Emirates', phone_code: '971', emoji: '🇦🇪', iso2: 'AE' },
  { name: 'Kuwait', phone_code: '965', emoji: '🇰🇼', iso2: 'KW' },
  { name: 'Qatar', phone_code: '974', emoji: '🇶🇦', iso2: 'QA' },
  { name: 'Bahrain', phone_code: '973', emoji: '🇧🇭', iso2: 'BH' },
  { name: 'Oman', phone_code: '968', emoji: '🇴🇲', iso2: 'OM' },
  { name: 'Jordan', phone_code: '962', emoji: '🇯🇴', iso2: 'JO' },
  { name: 'Lebanon', phone_code: '961', emoji: '🇱🇧', iso2: 'LB' },
  { name: 'Palestine', phone_code: '970', emoji: '🇵🇸', iso2: 'PS' },
  { name: 'Iraq', phone_code: '964', emoji: '🇮🇶', iso2: 'IQ' },
  { name: 'Syria', phone_code: '963', emoji: '🇸🇾', iso2: 'SY' },
  { name: 'Yemen', phone_code: '967', emoji: '🇾🇪', iso2: 'YE' },
  { name: 'Libya', phone_code: '218', emoji: '🇱🇾', iso2: 'LY' },
  { name: 'Sudan', phone_code: '249', emoji: '🇸🇩', iso2: 'SD' },
  { name: 'Algeria', phone_code: '213', emoji: '🇩🇿', iso2: 'DZ' },
  { name: 'Morocco', phone_code: '212', emoji: '🇲🇦', iso2: 'MA' },
  { name: 'Tunisia', phone_code: '216', emoji: '🇹🇳', iso2: 'TN' },
  { name: 'Mauritania', phone_code: '222', emoji: '🇲🇷', iso2: 'MR' },

  { name: 'United Kingdom', phone_code: '44', emoji: '🇬🇧', iso2: 'GB' },
  { name: 'United States', phone_code: '1', emoji: '🇺🇸', iso2: 'US' },
  { name: 'Canada', phone_code: '1', emoji: '🇨🇦', iso2: 'CA' },
  { name: 'Germany', phone_code: '49', emoji: '🇩🇪', iso2: 'DE' },
  { name: 'France', phone_code: '33', emoji: '🇫🇷', iso2: 'FR' },
  { name: 'Italy', phone_code: '39', emoji: '🇮🇹', iso2: 'IT' },
  { name: 'Spain', phone_code: '34', emoji: '🇪🇸', iso2: 'ES' },
  { name: 'Turkey', phone_code: '90', emoji: '🇹🇷', iso2: 'TR' },

  { name: 'India', phone_code: '91', emoji: '🇮🇳', iso2: 'IN' },
  { name: 'Pakistan', phone_code: '92', emoji: '🇵🇰', iso2: 'PK' },
  { name: 'Bangladesh', phone_code: '880', emoji: '🇧🇩', iso2: 'BD' },
  { name: 'China', phone_code: '86', emoji: '🇨🇳', iso2: 'CN' },
  { name: 'Japan', phone_code: '81', emoji: '🇯🇵', iso2: 'JP' },

  { name: 'Australia', phone_code: '61', emoji: '🇦🇺', iso2: 'AU' },
  { name: 'New Zealand', phone_code: '64', emoji: '🇳🇿', iso2: 'NZ' },
];